#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello_page:
  path: /
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: hello.html.twig

# welcome:
#   path: /welcome
#   controller:   Symfony\Bundle\FrameworkBundle\Controller\WelcomeController::index
#   defaults:
#     template: hello.html.twig
